image: python:3.12-slim

stages: [lint, test, build]

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"  # speeds up repeated installs

cache:
  key: ${CI_PROJECT_PATH_SLUG}-uv
  paths:
    - .cache/uv
    - .venv             # re-use the workspace venv across stages

before_script:
  - pip install --upgrade uv
  # install optional dev deps (ruff/pytest/coverage) from root extra group
  - uv sync --all-packages --group dev,test

lint:
  stage: lint
  script:
    - uv run ruff check .

test:
  stage: test
  needs: [lint]
  script:
    - uv run coverage run -m pytest
    - uv run coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml

build:
  stage: build
  needs: [test]
  script:
    - uv build --sdist --wheel --out dist/
  artifacts:
    paths:
      - dist/
